#!/usr/bin/env bash
# This script is displaying "To infinity and beyond" indefinitely.
# Cannot be terminated.

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invicible!!!"' SIGTERM
done
